replicaCount: 1

image:
  repository: myapp
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: NodePort
  port: 80
  nodePort: 30088 

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
